import { NextRequest } from 'next/server';
import { db } from '@/lib/db';
import {
  resolveTenant,
  isErrorResponse,
  corsResponse,
  withErrorHandler,
  handleCors,
} from '@/lib/api-helper';

// ============================================================
// GET /api/affiliates/stats — Affiliate dashboard stats
// ============================================================
// Returns aggregated affiliate statistics for the organization:
//   - Total revenue generated by affiliates
//   - Total commissions earned
//   - Total active affiliates
//   - Total referrals
//   - Top performers (sorted by revenue generated)
//
// Tenant-isolated by organizationId.
// ============================================================
export async function GET(request: NextRequest) {
  return withErrorHandler(async () => {
    const tenant = resolveTenant(request);
    if (isErrorResponse(tenant)) return tenant;

    const { searchParams } = new URL(request.url);
    const topLimit = Math.min(10, Math.max(1, parseInt(searchParams.get('top') || '5', 10)));

    // Aggregate stats
    const [totalStats, activeCount] = await Promise.all([
      db.affiliate.aggregate({
        where: { organizationId: tenant.organizationId },
        _sum: {
          totalRevenueGenerated: true,
          totalCommissionEarned: true,
          totalReferrals: true,
        },
        _count: true,
      }),
      db.affiliate.count({
        where: {
          organizationId: tenant.organizationId,
          isActive: true,
        },
      }),
    ]);

    // Top performers
    const topPerformers = await db.affiliate.findMany({
      where: { organizationId: tenant.organizationId },
      include: {
        user: {
          select: {
            id: true,
            name: true,
            email: true,
            avatar: true,
          },
        },
      },
      orderBy: { totalRevenueGenerated: 'desc' },
      take: topLimit,
    });

    return corsResponse({
      success: true,
      data: {
        totalAffiliates: totalStats._count,
        activeAffiliates: activeCount,
        totalRevenueGenerated: totalStats._sum.totalRevenueGenerated || 0,
        totalCommissionEarned: totalStats._sum.totalCommissionEarned || 0,
        totalReferrals: totalStats._sum.totalReferrals || 0,
        topPerformers,
      },
    });
  });
}

export async function OPTIONS() {
  return handleCors();
}
