import { NextRequest } from 'next/server';
import { db } from '@/lib/db';
import {
  resolveTenant,
  isErrorResponse,
  corsResponse,
  withErrorHandler,
  handleCors,
} from '@/lib/api-helper';

// ============================================================
// GET /api/affiliates/stats — Affiliate dashboard stats
// ============================================================
// Returns aggregated affiliate statistics for the organization:
//   - Total revenue generated by affiliates
//   - Total commissions earned
//   - Total active affiliates
//   - Total referrals
//   - Top performers (sorted by revenue generated)
//
// Tenant-isolated by organizationId.
// ============================================================
export async function GET(request: NextRequest) {
  return withErrorHandler(async () => {
    const tenant = resolveTenant(request);
    if (isErrorResponse(tenant)) return tenant;

    const { searchParams } = new URL(request.url);
    const topLimit = Math.min(10, Math.max(1, parseInt(searchParams.get('top') || '5', 10)));

    // Aggregate stats
    const [totalStats, activeCount] = await Promise.all([
      db.affiliate.aggregate({
        where: { organizationId: tenant.organizationId },
        _sum: {
          totalRevenueGenerated: true,
          totalCommissionEarned: true,
          totalReferrals: true,
        },
        _count: true,
      }),
      db.affiliate.count({
        where: {
          organizationId: tenant.organizationId,
          isActive: true,
        },
      }),
    ]);

    // Top performers
    const topPerformers = await db.affiliate.findMany({
      where: { organizationId: tenant.organizationId },
      orderBy: { totalRevenueGenerated: 'desc' },
      take: topLimit,
    });

    // Fetch user data separately (Affiliate has userId as plain string, not a Prisma relation)
    const topUserIds = [...new Set(topPerformers.map((a) => a.userId).filter(Boolean))];
    const topUsers = topUserIds.length > 0
      ? await db.user.findMany({
          where: { id: { in: topUserIds } },
          select: { id: true, name: true, email: true, avatar: true },
        })
      : [];
    const topUserMap = new Map(topUsers.map((u) => [u.id, u]));

    const enrichedTopPerformers = topPerformers.map((a) => ({
      ...a,
      user: topUserMap.get(a.userId) || null,
    }));

    // Recent referrals
    const recentReferrals = topPerformers.slice(0, 5).map((a) => ({
      id: a.id,
      code: a.code,
      userId: a.userId,
      userName: topUserMap.get(a.userId)?.name || 'Unknown',
      totalReferrals: a.totalReferrals,
      totalRevenueGenerated: a.totalRevenueGenerated,
      totalCommissionEarned: a.totalCommissionEarned,
      createdAt: a.createdAt,
    }));

    return corsResponse({
      success: true,
      data: {
        totalAffiliates: totalStats._count,
        activeAffiliates: activeCount,
        totalRevenueGenerated: totalStats._sum.totalRevenueGenerated || 0,
        totalCommissionEarned: totalStats._sum.totalCommissionEarned || 0,
        totalReferrals: totalStats._sum.totalReferrals || 0,
        topPerformers: enrichedTopPerformers,
        recentReferrals,
      },
    });
  });
}

export async function OPTIONS() {
  return handleCors();
}
