import { NextRequest } from 'next/server';
import { db } from '@/lib/db';
import {
  resolveTenant,
  isErrorResponse,
  withErrorHandler,
  handleCors,
  corsHeaders,
} from '@/lib/api-helper';

/**
 * GET /api/reports/export-pdf — Export tickets as branded PDF.
 *
 * Same filters as /api/reports/tickets:
 *   event, status, type, from, to, search
 *
 * Uses jsPDF + jspdf-autotable for PDF generation with org branding.
 */
export async function GET(request: NextRequest) {
  return withErrorHandler(async () => {
    const tenant = resolveTenant(request);
    if (isErrorResponse(tenant)) return tenant;

    const { searchParams } = new URL(request.url);

    const eventId = searchParams.get('event');
    const status = searchParams.get('status');
    const type = searchParams.get('type');
    const from = searchParams.get('from');
    const to = searchParams.get('to');
    const search = searchParams.get('search');

    // Build where clause
    const where: Record<string, unknown> = {
      event: { organizationId: tenant.organizationId },
    };

    if (eventId) where.eventId = eventId;
    if (status) where.status = status;
    if (type) where.ticketType = type;

    if (from || to) {
      where.createdAt = {};
      if (from) (where.createdAt as Record<string, unknown>).gte = new Date(from);
      if (to) (where.createdAt as Record<string, unknown>).lte = new Date(to);
    }

    if (search) {
      where.OR = [
        { holderName: { contains: search } },
        { ticketCode: { contains: search } },
      ];
    }

    // Fetch tickets and org details in parallel
    const [tickets, org] = await Promise.all([
      db.ticket.findMany({
        where,
        include: {
          event: { select: { id: true, name: true } },
        },
        orderBy: { createdAt: 'desc' },
      }),
      db.organization.findUnique({
        where: { id: tenant.organizationId },
        select: { name: true, primaryColor: true, logoUrl: true },
      }),
    ]);

    // Dynamic import of jsPDF (server-side only)
    const { default: jsPDF } = await import('jspdf');
    const { default: autoTable } = await import('jspdf-autotable');

    const doc = new jsPDF('landscape', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();

    // Branding header bar
    const primaryColor = org?.primaryColor || '#059669';
    doc.setFillColor(primaryColor);
    doc.rect(0, 0, pageWidth, 22, 'F');

    // Organization name
    doc.setTextColor('#ffffff');
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(org?.name || 'SmartTicketQR', 14, 15);

    // Logo placeholder if URL is not a data URL
    if (org?.logoUrl && !org.logoUrl.startsWith('data:')) {
      doc.setFontSize(8);
      doc.setFont('helvetica', 'italic');
      doc.text(`[Logo: ${org.logoUrl}]`, pageWidth - 14, 15, { align: 'right' });
    } else if (org?.logoUrl?.startsWith('data:')) {
      try {
        doc.addImage(org.logoUrl, 'PNG', pageWidth - 40, 4, 26, 14);
      } catch {
        // Silently skip if image fails
      }
    }

    // Report title
    doc.setTextColor('#1f2937');
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Ticket Report', 14, 32);

    // Date info
    const today = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
    doc.setFontSize(9);
    doc.setTextColor('#6b7280');
    doc.text(`Generated: ${today} | Total tickets: ${tickets.length}`, 14, 38);

    // Table data
    const tableData = tickets.map((t) => [
      t.ticketCode,
      t.event?.name || '-',
      t.holderName,
      t.ticketType,
      `${t.price.toFixed(2)} ${t.currency}`,
      t.status,
      t.issuedAt ? t.issuedAt.toLocaleDateString() : '-',
    ]);

    // Create auto table
    autoTable(doc, {
      head: [['Code', 'Event', 'Holder', 'Type', 'Price', 'Status', 'Date']],
      body: tableData,
      startY: 42,
      theme: 'striped',
      headStyles: {
        fillColor: [5, 150, 105],
        textColor: '#ffffff',
        fontStyle: 'bold',
        fontSize: 9,
      },
      bodyStyles: {
        fontSize: 8,
        textColor: '#374151',
      },
      alternateRowStyles: {
        fillColor: '#f9fafb',
      },
      styles: {
        cellPadding: 2,
        lineColor: '#e5e7eb',
        lineWidth: 0.1,
      },
      columnStyles: {
        0: { cellWidth: 32 }, // Code
        2: { cellWidth: 40 }, // Holder
      },
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      const pageHeight = doc.internal.pageSize.getHeight();
      doc.setFontSize(7);
      doc.setTextColor('#9ca3af');
      doc.text(
        `Generated by SmartTicketQR — ${today} — Page ${i} of ${pageCount}`,
        pageWidth / 2,
        pageHeight - 6,
        { align: 'center' }
      );
    }

    // Return PDF as buffer
    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
    const todayStr = new Date().toISOString().split('T')[0];
    const filename = `rapport_tickets_${todayStr}.pdf`;

    return new Response(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
        ...corsHeaders,
      },
    });
  });
}

export async function OPTIONS() {
  return handleCors();
}
